### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cyouh95** [oforir/tea_cozy#1]
### Criteria 1: HTML Structure  
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ HTML implementation enables proper use of flexbox. HTML structure reflects the grouping and flow of content in the web browser.
 
### Criteria 2: Visual Layout
* _Score Level:_ 3 (Meets Expectations)
* _Comment(s):_ Layout matches the design spec in most sections. Only discrepancy is the extra `padding-top` [here](https://github.com/oforir/tea_cozy/blob/3b99495b09060ac3bf3e70d1533b4e764b673868/resources/css/styles.css#L80), which you are correct in believing it was not needed. Was there any reason you thought otherwise?
 
### Criteria 3: Use of Flexbox
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Flexbox properties are correctly applied to flex containers and flex items throughout. Flexbox is used properly and is the primary way of positioning.
 
### Criteria 4: Implementation of Design Specification and Content
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ The page includes all style and content provided in the design specification.
 
### Overall Score: 15/16

Nice job with this project! It looks like you have a solid understanding of how HTML and CSS work together for display of content. You were able to recreate all the main components of this webpage so well done!

Great job formatting and commenting your code as well! And to address some of your comments: [This](https://github.com/oforir/tea_cozy/blob/3b99495b09060ac3bf3e70d1533b4e764b673868/index.html#L33) container seems to be the perfect height actually. Did you mean to point to this [div](https://github.com/oforir/tea_cozy/blob/3b99495b09060ac3bf3e70d1533b4e764b673868/index.html#L38)? This minor discrepancy could be due to not setting `display: block;` on the `img`s. ([Here](https://stackoverflow.com/a/15357037/6373540) is some more info). 

And it seems [this](https://github.com/oforir/tea_cozy/blob/3b99495b09060ac3bf3e70d1533b4e764b673868/resources/css/styles.css#L93) detail is indeed missing from the spec - good catch! But don't stress too much about the specific dimensions - it looks like you have a good understanding of display and layout of elements, and that's what's important.

As a further challenge, try creating your own page from scratch without the use of any specs or template. You definitely already have a good sense of how to organize and structure your code - this will be great practice for continuing to build your skills! Have fun :)

**Comment by oforir** [comment]
Thanks for reviewing my project cyouh95, very much appreciated!
